version: "3.3"

services:
    app:
        build:
            context: .
            dockerfile: docker/app/Dockerfile
        container_name: ci31_app
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
        environment:
            - CI_ENV=development
            - APP_BASE_URL=http://localhost:8080
            - DB_HOST=db
            - DB_NAME=todo_db
            - DB_USER=todo_user
            - DB_PASS=todo_pass
        depends_on:
            - db

    db:
        image: mysql:5.7
        container_name: ci31_db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: todo_db
            MYSQL_USER: todo_user
            MYSQL_PASSWORD: todo_pass
        ports:
            - "3307:3306"
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
    dbdata:
